---
# Dotfiles-VM Installation Playbook
# Installs bash-based configurations for Fedora VM environment

- name: Install dotfiles-vm
  hosts: localhost
  connection: local
  become: false

  vars:
    dotfiles_vm_dir: "{{ lookup('env', 'PWD') }}"
    stow_packages:
      - bash
      - git
      - nvim
      - ripgrep
      - tmux

  tasks:
    - name: Display installation directory
      ansible.builtin.debug:
        msg: "Installing dotfiles-vm from: {{ dotfiles_vm_dir }}"

    - name: Install prerequisite packages
      become: true
      ansible.builtin.dnf:
        name:
          - awscli2
          - bat
          - clangd
          - curl
          - fd-find
          - fzf
          - git
          - git-delta
          - jq
          - lazygit
          - lsof
          - mise
          - neovim
          - python3-pip
          - ripgrep
          - stow
          - tmux
          - tree
          - unzip
          - wget
          - xclip
          - xorg-x11-xauth
        state: present
      tags: packages

    - name: Initialize and update git submodules
      ansible.builtin.command:
        cmd: git submodule update --init --recursive
        chdir: "{{ dotfiles_vm_dir }}"
      register: submodule_result
      changed_when: "'Cloning into' in submodule_result.stderr or 'Submodule path' in submodule_result.stderr"
      tags: submodules

    - name: Stow dotfiles packages
      ansible.builtin.command:
        cmd: stow -d "{{ dotfiles_vm_dir }}/stow" -t "{{ ansible_env.HOME }}" "{{ item }}"
      loop: "{{ stow_packages }}"
      register: stow_result
      changed_when: stow_result.rc == 0
      tags: stow

    - name: Enable ForwardX11 in /etc/ssh/ssh_config
      become: true
      ansible.builtin.lineinfile:
        path: /etc/ssh/ssh_config
        regexp: '^#?\s*ForwardX11\s+'
        line: "    ForwardX11 yes"
        state: present
      tags: ssh

    - name: Create nvim-local config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/nvim-local"
        state: directory
        mode: "0755"
      tags: nvim

    - name: Clone friendly-snipeets repository
      ansible.builtin.git:
        repo: https://github.com/aljendro/friendly-snippets.git
        dest: "{{ ansible_env.HOME }}/.config/nvim-local/friendly-snippets"
        version: HEAD
      tags: nvim

    - name: Create start_project.local.sh script
      ansible.builtin.copy:
        dest: "{{ dotfiles_vm_dir }}/start_project.local.sh"
        mode: "0755"
        content: |
          #!/bin/bash

          session="dotfiles"
          tmux has-session -t $session 2>/dev/null

          if [ $? != 0 ]; then
            tmux new -d -t $session
            tmux rename-window -t $session:1 "Main"
            tmux send -t $session:1 "nvim README.md" C-m
          fi

          echo "$session"
      tags: scripts
